name: .NET

on:
  push:
    branches: [ main ]
    paths: [ 'src/**', '.github/workflows/**']
  pull_request:
    branches: [ '**' ]
    paths: [ 'src/**', '.github/workflows/**' ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUILD_CONFIGURATION: Release
    steps:
    - name: Checkout branch
      uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
      env:
        NUGET_AUTH_TOKEN: ${{secrets.NUGET_AUTH_TOKEN}}
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration $BUILD_CONFIGURATION
    - name: Test
      run: dotnet test --no-build --configuration $BUILD_CONFIGURATION --verbosity normal
    - name: Pack
      run: dotnet pack --no-build --configuration $BUILD_CONFIGURATION
    - name: Upload NuGet Package Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: nuget-packages
        path: src/**/*.nupkg

  publish:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    needs: [ 'build' ]

    steps:
    - name: Download NuGet Package Artifacts
      uses: actions/download-artifact@v2
      with:
        name: nuget-packages
    - name: Publish NuGet Packages
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      run: dotnet nuget push src/**/*.nupkg
